#Requires -Version 5.1
<#
.SYNOPSIS
  Fully automated Windows installer build for Merphi Audio Inspector.
#>
Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$ProjectRoot = $PSScriptRoot
$ToolsDir = Join-Path $ProjectRoot ".tools"
$InnoDir = Join-Path $ToolsDir "InnoSetup"
$IsccPath = Join-Path $InnoDir "ISCC.exe"
$InnoInstaller = Join-Path $ToolsDir "innosetup-installer.exe"
$InstallerDir = Join-Path $ProjectRoot "installer"
$OutputDir = Join-Path $InstallerDir "output"
$IssPath = Join-Path $InstallerDir "MerphiAudioInspector.iss"
$AppExe = Join-Path $ProjectRoot "dist\Merphi Audio Inspector.exe"
$InnoDownloadUrl = "https://jrsoftware.org/download.php/is.exe"

function Write-Step($Message) {
    Write-Host ""
    Write-Host "==> $Message" -ForegroundColor Cyan
}

function Ensure-Directory($Path) {
    if (-not (Test-Path $Path)) {
        New-Item -ItemType Directory -Path $Path -Force | Out-Null
    }
}

function Get-InnoSetupCompiler {
    if (Test-Path $IsccPath) { return $IsccPath }
    $globalIscc = Get-Command ISCC.exe -ErrorAction SilentlyContinue
    if ($globalIscc) { return $globalIscc.Source }

    Write-Step "Downloading Inno Setup Compiler"
    Ensure-Directory $ToolsDir
    if (-not (Test-Path $InnoInstaller)) {
        Invoke-WebRequest -Uri $InnoDownloadUrl -OutFile $InnoInstaller -UseBasicParsing
    }

    Write-Step "Installing Inno Setup silently to $InnoDir"
    if (Test-Path $InnoDir) { Remove-Item -Recurse -Force $InnoDir }
    Ensure-Directory $InnoDir

    $installArgs = @("/VERYSILENT", "/SUPPRESSMSGBOXES", "/NORESTART", "/SP-", "/DIR=`"$InnoDir`"")
    $proc = Start-Process -FilePath $InnoInstaller -ArgumentList $installArgs -Wait -PassThru
    if ($proc.ExitCode -ne 0) { throw "Inno Setup installer exited with code $($proc.ExitCode)" }
    if (-not (Test-Path $IsccPath)) { throw "ISCC.exe not found after Inno Setup install: $IsccPath" }
    return $IsccPath
}

function Write-IssFile {
    $appExeName = Split-Path $AppExe -Leaf
    $iss = @'
; Auto-generated by build_installer.ps1 — Merphi Audio Inspector
#define MyAppName "Merphi Audio Inspector"
#define MyAppPublisher "Merphi Music Group"
#define MyAppExeName "{EXE_NAME}"
#define MyAppVersion "1.0.0"

[Setup]
AppId={{A7B3C9D1-4E2F-5A6B-8C9D-0E1F2A3B4C5D}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
SetupIconFile=..\icon.ico
WizardSmallImageFile=logo.bmp
OutputDir=output
OutputBaseFilename=Merphi_Setup
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest
ArchitecturesInstallIn64BitMode=x64compatible
UninstallDisplayIcon={app}\{#MyAppExeName}

[Languages]
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"; LicenseFile: "EULA_ru.txt"
Name: "english"; MessagesFile: "compiler:Default.isl"; LicenseFile: "EULA_en.txt"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "..\dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[INI]
Filename: "{localappdata}\Merphi Audio Inspector\config.ini"; Section: "Merphi"; Key: "Language"; String: "{language}"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
'@ -replace '\{EXE_NAME\}', $appExeName

    Set-Content -Path $IssPath -Value $iss -Encoding UTF8
}

Write-Step "Checking application executable"
$iconFile = Join-Path $ProjectRoot "icon.ico"
if (-not (Test-Path $iconFile)) { throw "Application icon not found: $iconFile" }
if (-not (Test-Path $AppExe)) { throw "Application not found: $AppExe`nBuild it first with PyInstaller." }

Ensure-Directory $InstallerDir
Ensure-Directory $OutputDir

Write-Step "Generating EULA files and wizard logo via Python"
python (Join-Path $ProjectRoot "prepare_installer_assets.py")
if ($LASTEXITCODE -ne 0) { throw "prepare_installer_assets.py failed with exit code $LASTEXITCODE" }

Write-Step "Generating Inno Setup script"
Write-IssFile

$iscc = Get-InnoSetupCompiler

Write-Step "Compiling installer with ISCC"
Push-Location $InstallerDir
try {
    & $iscc $IssPath
    if ($LASTEXITCODE -ne 0) { throw "ISCC failed with exit code $LASTEXITCODE" }
}
finally { Pop-Location }

$setupExe = Join-Path $OutputDir "Merphi_Setup.exe"
if (-not (Test-Path $setupExe)) { throw "Expected installer not found: $setupExe" }

Write-Host ""
Write-Host "SUCCESS: Installer ready at:" -ForegroundColor Green
Write-Host "  $setupExe" -ForegroundColor Green
$sizeMb = [math]::Round((Get-Item $setupExe).Length / 1MB, 1)
Write-Host "  Size: $sizeMb MB" -ForegroundColor Green
